JE-60834 [Plesk] Deployment from marketplace get's stuck during insta…
jelastic-jps/plesk pull request #10
Opened 2021-11-29 09:53 UTC by lazarenkoalexey

…llation

2021-11-29 18:23 UTC, SlavaKatiukha requested changes

2021-11-29 18:23 UTC, SlavaKatiukha commented on manifest.jps
> +      while [ $(plesk bin cloning --status) -ne 0 ]; do { sleep 5; counter=$((counter+5)); [[ "$timeout" == "$counter" ]] && { plesk bin cloning -u -prepare-public-image false; break; } } done
use `timeout 300 bash -c '...' `

2021-11-30 10:58 UTC, lazarenkoalexey commented on manifest.jps
> +      while [ $(plesk bin cloning --status) -ne 0 ]; do { sleep 5; counter=$((counter+5)); [[ "$timeout" == "$counter" ]] && { plesk bin cloning -u -prepare-public-image false; break; } } done
applied in the same pull request

2021-12-01 07:34 UTC, SlavaKatiukha approved these changes

2022-04-13 12:46 UTC, merged